### ISSUE TITLE
LLaVA > v0

### ISSUE THREAD

**Issue by alexsax** [concept-graphs/concept-graphs#14]
Hi folks,

Thanks for releasing the code for you preprint!

I'd like to test this out as a baseline -- ideally with LLaVA 1.5 so the baseline is as strong as possible. However, it looks like the tokenization changed between LLaVA v0 and v1. I've verified that my environment can execute the web server in the LLaVA repo, and the captioning model there is able to parse and respond to images. 

However, the LLaVA "tweaked" model in concept-graphs doesn't seems to suport the new tokenization, and it throws the following error when extracting captions:
```
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [143,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
  0%|                                                                                                                                                                                      | 0/10 [00:01<?, ?it/s]
  0%|                                                                                                                                                                                      | 0/61 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/private/home/ssax/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 966, in <module>
    main()
  File "/private/home/ssax/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 952, in main
    extract_node_captions(args)
  File "/private/home/ssax/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 370, in extract_node_captions
    outputs = chat(query=query, image_features=image_features)
  File "/private/home/ssax/concept-graphs/conceptgraph/llava/llava_model.py", line 719, in __call__
    output_ids = self.model.generate(
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/private/home/ssax/concept-graphs/conceptgraph/llava/llava_model.py", line 449, in forward
    outputs = self.model(
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/private/home/ssax/concept-graphs/conceptgraph/llava/llava_model.py", line 202, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/private/home/ssax/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
```

Any suggestions about how to use LLaVA 1.5?

Thanks!

**Comment by krrish94** [comment]
Hi @alexsax, we've been porting the code (and benchmarking) wrt LLaVA1.5 too; so this is timely indeed.

We have a modified version of the llava repo here - https://github.com/3d-language-model/llava-mod

You could use this repo instead; and replace the `LLaVAChat` class in the current concept-graphs codebase with [this class](https://github.com/3d-language-model/llava-mod/blob/main/scripts/standalone_llava_chat.py).

[Here](https://github.com/3d-language-model/llava-mod/blob/main/scripts/standalone_llava_chat.py#L126-L142) is a code snippet to use this class. This should be plug-and-play; let us know if you encounter any issues.

**Comment by georgegu1997** [comment]
Assuming this issue is fixed and closing it. Feel free to re-open if needed.

**Comment by ZhangCYG** [comment]
Since the original LLaVAChat class in the current concept-graphs codebase is different with what in the provided repo, I wonder if I subsitute all the calls of LLaVAChat in ConceptGraph to the class the provided repo?
