### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by Mischievous707** [concept-graphs/concept-graphs#22]
I face the same problem, and I follow the suggestion given by "For debugging consider passing CUDA_LAUNCH_BLOCKING=1." . However, there is still an error when initializing the LLaVA chat.
Error detail：
args.masking_option: none
[2024-01-05 11:12:52,016] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loaded 59 objects
['footrest', 'cat', 'boat', 'vanity', 'dresser', 'door', 'other item', 'sink', 'blanket', 'swivel chair', 'nightstand', 'pillow', 'couch', 'sculpture', 'curtain', 'daybed', 'armchair', 'round table', 'anchor', 'bay window', 'chair', 'fill', 'cabinet', 'stool', 'window', 'drawer', 'pad', 'table', 'lead to', 'side table', 'furniture', 'blind', 'white', 'ceiling', 'hang', 'lamp', 'ceiling fan', 'glass table', 'floor', 'den', 'hassock', 'wall']
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00, 2.40s/it]
LLaVA chat initialized...
0%| | 0/59 [00:00<?, ?it/sUser: Describe the central object in the image. | 0/10 [00:00<?, ?it/s]
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [96,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [97,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [98,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [99,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [100,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [101,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [102,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [103,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [104,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [105,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [106,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [107,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [108,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [109,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [110,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [111,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [112,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [113,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [114,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [115,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [116,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [117,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [118,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [119,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [120,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [121,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [122,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [123,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [124,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [125,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [126,0,0] Assertion srcIndex < srcSelectDimSize failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [252,0,0], thread: [127,0,0] Assertion srcIndex < srcSelectDimSize failed.
0%| | 0/10 [00:01<?, ?it/s]
0%| | 0/59 [00:01<?, ?it/s]
Traceback (most recent call last):
File "/data/maruifei/code/concept-graphs-main/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 966, in
main()
File "/data/maruifei/code/concept-graphs-main/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 952, in main
extract_node_captions(args)
File "/data/maruifei/code/concept-graphs-main/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 370, in extract_node_captions
outputs = chat(query=query, image_features=image_features)
File "/data/maruifei/code/concept-graphs-main/conceptgraph/llava/llava_model.py", line 731, in call
output_ids = self.model.generate(
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
return self.sample(
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
outputs = self(
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/data/maruifei/code/concept-graphs-main/conceptgraph/llava/llava_model.py", line 447, in forward
outputs = self.model(
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/data/maruifei/code/concept-graphs-main/conceptgraph/llava/llava_model.py", line 201, in forward
inputs_embeds = self.embed_tokens(input_ids)
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
return F.embedding(
File "/data/maruifei/miniconda3/envs/conceptgraph/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by sachinb20** [comment]
Facing the same issue :(

[2024-01-07 08:43:24,533] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loaded 55 objects
['bedding', 'art', 'linen', 'dog bed', 'headboard', 'mattress', 'pad', 'vanity', 'chair', 'twin', 'tree', 'throw pillow', 'nightstand', 'frame', 'plant', 'wall', 'closet', 'picture frame', 'cabinet', 'picture', 'vase', 'bed', 'drawing', 'dormitory', 'mirror', 'light', 'window', 'side table', 'tub', 'bay window', 'screen door', 'garment', 'towel', 'other item', 'shower', 'table', 'lamp', 'ceiling fan', 'comfort', 'floor', 'gray', 'sink', 'hassock', 'sweater', 'dresser', 'hang', 'pillow', 'couch', 'chiffonier', 'white', 'drawer', 'curtain', 'make', 'mat', 'bath', 'ceiling', 'blanket', 'clothe', 'bedcover', 'stool', 'quilt', 'cloth', 'sheet', 'toilet bowl', 'blind', 'jacket', 'armchair']
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.43s/it]
LLaVA chat initialized...
  0%|                                                                                                                                           | 0/55 [00:00<?, ?it/sUser: Describe the central object in the image.                                                                                                  | 0/10 [00:00<?, ?it/s]
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [207,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [99,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [100,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [101,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [102,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [103,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [104,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [105,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [106,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [107,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [108,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [109,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [110,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [111,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [112,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [113,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [114,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [115,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [116,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [117,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [118,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [119,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [120,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [121,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [122,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [123,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [124,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [366,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
  0%|                                                                                                                                           | 0/10 [00:00<?, ?it/s]
  0%|                                                                                                                                           | 0/55 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 966, in <module>
    main()
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 952, in main
    extract_node_captions(args)
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/scenegraph/build_scenegraph_cfslam.py", line 370, in extract_node_captions
    outputs = chat(query=query, image_features=image_features)
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/llava/llava_model.py", line 721, in __call__
    output_ids = self.model.generate(
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/llava/llava_model.py", line 447, in forward
    outputs = self.model(
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hypatia/Sachin_Workspace/concept-graphs/conceptgraph/llava/llava_model.py", line 201, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/hypatia/miniconda3/envs/conceptgraph2/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Mischievous707** [comment]
I have tracked this issue and found that after "self.tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)",the "len(self.tokenizer.vocab)" become 32001, but "len(self.tokenizer.vocab_size)" is 32000. So I resize the token embeddings with this  command

**Comment by Mischievous707** [comment]
![Uploading 屏幕截图 2024-01-08 194051.png…]()
> I have tracked this issue and found that after "self.tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)",the "len(self.tokenizer.vocab)" become 32001, but "len(self.tokenizer.vocab_size)" is 32000. So I resize the token embeddings with this command



> I have tracked this issue and found that after "self.tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)",the "len(self.tokenizer.vocab)" become 32001, but "len(self.tokenizer.vocab_size)" is 32000. So I resize the token embeddings with this command

**Comment by Mischievous707** [comment]
<img width="517" alt="image" src="https://github.com/concept-graphs/concept-graphs/assets/153591473/abe64dd0-1bf3-44ee-aa08-4b732873fc74">

**Comment by Mischievous707** [comment]
I have tracked this issue and found that after "self.tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)", the "len(self.tokenizer.vocab)" become 32001, but "len(self.tokenizer.vocab_size)" is 32000. So I resize the token embeddings with this command

        ## Resize the tokenizer to accomodate the new tokens 32000-32001
        self.model.resize_token_embeddings(len(self.tokenizer.vocab))

but another problem arose，like 

args.masking_option: none
[2024-01-08 19:13:14,954] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loaded 59 objects
['footrest', 'cat', 'boat', 'vanity', 'dresser', 'door', 'other item', 'sink', 'blanket', 'swivel chair', 'nightstand', 'pillow', 'couch', 'sculpture', 'curtain', 'daybed', 'armchair', 'round table', 'anchor', 'bay window', 'chair', 'fill', 'cabinet', 'stool', 'window', 'drawer', 'pad', 'table', 'lead to', 'side table', 'furniture', 'blind', 'white', 'ceiling', 'hang', 'lamp', 'ceiling fan', 'glass table', 'floor', 'den', 'hassock', 'wall']
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.57s/it]
LLaVA chat initialized...
  0%|                                                                                                                          | 0/59 [00:00<?, ?it/sUser: Describe the central object in the image.                                                                                 | 0/10 [00:00<?, ?it/s]
LLaVA: the image with a link to the URL.
                                                                                                                                                     User: Describe the central object in the image.                                                                        | 1/10 [01:41<15:14, 101.63s/it]
LLaVA: the image) with an opening.
                                                                                                                                                     User: Describe the central object in the image.                                                                         | 2/10 [02:11<07:53, 59.14s/it]
LLaVA: the image, and the image, and the image, and the message, and the image. (and the URL) and the image, and the URL) and the message.

LLaVA generates irrelevant caption. I haven't found the cause of this problem yet. Can someone help me？

**Comment by Mischievous707** [comment]
The truth is, my llava weight file version is v1.5-7b, I changed it to v0-7b, and he succeeded！！

**Comment by Deok-min** [comment]
I also faced the same issue. I tried to run it with liuhaotian/LLaVA-7b-delta-v0 model, then there is no such error.
But it generates meaningless captions. Even it is not an English.
![image](https://github.com/concept-graphs/concept-graphs/assets/48019048/9f670f03-6cc7-4910-92c0-24f7bdf17415)

**Comment by georgegu1997** [comment]
**Note**: this issue is a continuation of # # #11 , where the following command was run and `CUDA error: device-side assert triggered` is triggered. 

```
python scenegraph/build_scenegraph_cfslam.py \
--mode extract-node-captions \
--cachedir /media/local/gaurav/Music/Gaurav/concept-graphs/Datasets/Replica/room0/sg_cache \
--mapfile /media/local/gaurav/Music/Gaurav/concept-graphs/Datasets/Replica/room0/pcd_saves/full_pcd_ram_withbg_allclasses_overlap_maskconf0.25_simsum1.2_dbscan.1_post.pkl.gz \
--class_names_file /media/local/gaurav/Music/Gaurav/concept-graphs/Datasets/Replica/room0/gsa_classes_ram_withbg_allclasses.json
```

**Comment by georgegu1997** [comment]
I am not able to reproduce this error on my side. I suspect this could be a version difference between the LLaVA codebase we are using. For your reference, conceptgraph has been tested with [LLaVA code](https://github.com/haotian-liu/LLaVA) at this [commit](https://github.com/haotian-liu/LLaVA/commit/8fc54a09a6be74b2abd913c468fb3d42ae826194). Also it includes a small change as mentioned in the [readme](https://github.com/concept-graphs/concept-graphs?tab=readme-ov-file#extract-object-captions-and-build-scene-graphs). 

Please try to checkout the code at that commit and try running the script again. Thanks!

**Comment by BIT-DYN** [comment]
Hi, @georgegu1997 , thanks for such an excellent job.
I actually had the exact same problem.
I am using the latest [llava](https://github.com/haotian-liu/LLaVA) version, and the [llava-v1.5-7b](https://huggingface.co/liuhaotian/llava-v1.5-7b/tree/main) weights (tested without problems according to the official llava journey).

Do you have any suggestions as to where the problem lies?

**Comment by BIT-DYN** [comment]
Thanks, I have solved this problem by loading the model [LLaVA-7B-v0](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#:~:text=Instructions%3A,delta%20liuhaotian/LLaVA%2D7b%2Ddelta%2Dv0).

The model llama-7b can be downloaded [here](https://huggingface.co/huggyllama/llama-7b/tree/main).

**Comment by krrish94** [comment]
Hi all,

Thanks for all this discussion so far. The issue, as @BIT-DYN points out, is that during our development, we used older versions of the llava repo and model weights.

We will shortly update this repo to use the latest llava repo and support model weights from the newer llama/llava variants.

**Comment by georgegu1997** [comment]
Seems the issue can be solved by using the older LLaVA codebase and checkpoint. I have updated the readme about this and am closing this issue.

**Comment by wangjinhoon** [comment]
> Thanks, I have solved this problem by loading the model [LLaVA-7B-v0](https://github.com/haotian-liu/LLaVA/blob/main/docs/MODEL_ZOO.md#:~:text=Instructions%3A,delta%20liuhaotian/LLaVA%2D7b%2Ddelta%2Dv0).
> 
> The model llama-7b can be downloaded [here](https://huggingface.co/huggyllama/llama-7b/tree/main).

Hello, thank you for providing great code. I was running the code using LLaVA-7b-delta-v0, but LLaVA generated an incorrect explanation (not in English), so I tried using the llama-7b you mentioned.

However, I encountered this error.
```
AttributeError: 'LlavaConfig' object has no attribute 'mm_vision_tower'

```
Could you help me with this?

**Comment by lzm-bit** [comment]
> I also faced the same issue. I tried to run it with liuhaotian/LLaVA-7b-delta-v0 model, then there is no such error. But it generates meaningless captions. Even it is not an English. ![image](https://github.com/concept-graphs/concept-graphs/assets/48019048/9f670f03-6cc7-4910-92c0-24f7bdf17415)

I also encountered this problem, how did you solve it?

**Comment by lzm-bit** [comment]
> > I also faced the same issue. I tried to run it with liuhaotian/LLaVA-7b-delta-v0 model, then there is no such error. But it generates meaningless captions. Even it is not an English. ![image](https://github.com/concept-graphs/concept-graphs/assets/48019048/9f670f03-6cc7-4910-92c0-24f7bdf17415)
> 
> I also encountered this problem, how did you solve it?

i solve this problem, i download the file **huggyllama/llama-7b** and the **liuhaotian/LLaVA-7b-delta-v0**. then use the _python3 -m llava.model.apply_delta   --base huggyllama/llama-7b  --target huggyllama/llama-7b/LLaVA-7B-v0    --delta liuhaotian/LLaVA-7b-delta-v0_ generate the **LLaVA-7B-v0**, you can use this **LLaVA-7B-v0** solve this problem and get the correct result. for example: 

<img width="1000" height="1500" alt="Image" src="https://github.com/user-attachments/assets/058d922d-5ede-42e4-8f69-af07252200a9" />
